// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	// Code A code representing the type of the error, same as error name in Go.
	Code string `json:"code"`

	// Message A message detailing the error.
	Message string `json:"message"`
}

// PowerConsumption defines model for PowerConsumption.
type PowerConsumption struct {
	// CpuMilli The amount of CPUs required by each workload.
	CpuMilli int `json:"cpu_milli"`

	// NumWorkloads The amount of workloads have to be allocated.
	NumWorkloads int `json:"num_workloads"`

	// WattIncreases The estimated power increase per workload.
	WattIncreases *[]float64 `json:"watt_increases,omitempty"`
}

// PostNamespacesNsEstimatorsNameValuesPowerconsumptionJSONRequestBody defines body for PostNamespacesNsEstimatorsNameValuesPowerconsumption for application/json ContentType.
type PostNamespacesNsEstimatorsNameValuesPowerconsumptionJSONRequestBody = PowerConsumption
