apiVersion: waofed.bitmedia.co.jp/v1beta1
kind: Estimator
metadata:
  namespace: default
  name: default
spec:
  # default settings applied to all nodes
  defaultNodeConfig:
    nodeMonitor:
      refreshInterval: 5s
      agents:
        - type: IPMIExporter
          endpoint: http://localhost:9200/metrics
        - type: DifferentialPressureAPI
          endpoint: http://localhost:8080
    powerConsumptionPredictor:
      type: MLServer
      endpoint: http://wao-mlserver.default.svc.cluster.local:8080
  # override the default
  nodeConfigOverrides:
    # node "controlplane0"
    controlplane0:
      nodeMonitor:
        agents:
          - type: None
      powerConsumptionPredictor:
        type: None
    # node "redfishworker0"
    redfishworker0:
      nodeMonitor:
        agents:
          - type: Redfish
            endpoint: http://localhost/redfish/v1
          - type: DifferentialPressureAPI
            endpoint: http://localhost:8080
